Repository pkoutoupis/rapiddisk, pull requests merged in 2023-02, with the labels that each got.

#145 Defect/minor cleanup and 9.0 release
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  conf/Makefile
  conf/rapiddisk.sh.pacemaker
  conf/rapiddisk.sh.rgmanager
  doc/Makefile
  doc/rapiddisk.1
  doc/rapiddiskd.1
  module/Makefile
  module/dkms.conf
  module/rapiddisk-cache.c
  module/rapiddisk.c
  pkg/debian/changelog
  pkg/debian/copyright
  pkg/rpm/rapiddisk.spec.rhel
  pkg/rpm/rapiddisk.spec.sles
  scripts/nvmet/nvmet-generate-hostnqn.sh
  scripts/nvmet/nvmet-tune-system.sh
  scripts/rapiddisk-legacy/rapiddisk-legacy.sh
  src/Makefile
  src/common.h
  src/json.c
  src/json.h
  src/main.c
  src/main.h
  src/net.c
  src/nvmet.c
  src/nvmet.h
  src/rapiddiskd.c
  src/rapiddiskd.h
  src/rdsk.c
  src/rdsk.h
  src/sys.c
  src/sys.h
  src/utils.c
  src/utils.h
  test/Makefile
  test/rxflush.c
  test/rxio.c
  test/rxioctl.c
  test/rxro.c
Labels: bug, enhancement

#151 Disable unnecessary writeback cache in rapiddisk module (#147)
  module/rapiddisk.c
Labels: enhancement

#157 Remove absolute path from service file
  conf/rapiddiskd.service
Labels: bug
